package cayenne.DBobjects.auto;

import java.util.List;

/** Class _Student was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Student extends org.apache.cayenne.CayenneDataObject {

    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String USER_NAME_PROPERTY = "userName";
    public static final String ENROLLMENT_PROPERTY = "enrollment";
    public static final String HISTORY_PROPERTY = "history";

    public static final String ID_PK_COLUMN = "ID";

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }
    
    
    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }
    
    
    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }
    
    
    public void setUserName(String userName) {
        writeProperty("userName", userName);
    }
    public String getUserName() {
        return (String)readProperty("userName");
    }
    
    
    public void addToEnrollment(cayenne.DBobjects.Class obj) {
        addToManyTarget("enrollment", obj, true);
    }
    public void removeFromEnrollment(cayenne.DBobjects.Class obj) {
        removeToManyTarget("enrollment", obj, true);
    }
    public List getEnrollment() {
        return (List)readProperty("enrollment");
    }
    
    
    public void addToHistory(cayenne.DBobjects.Attempt obj) {
        addToManyTarget("history", obj, true);
    }
    public void removeFromHistory(cayenne.DBobjects.Attempt obj) {
        removeToManyTarget("history", obj, true);
    }
    public List getHistory() {
        return (List)readProperty("history");
    }
    
    
}
