package cayenne.DBobjects.auto;

/** Class _Attempt was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Attempt extends org.apache.cayenne.CayenneDataObject {

    public static final String CAUSE_PROPERTY = "cause";
    public static final String DATE_PROPERTY = "date";
    public static final String STUDENT_CODE_PROPERTY = "studentCode";
    public static final String PROBLEM_PROPERTY = "problem";
    public static final String STUDENT_PROPERTY = "student";

    public static final String ID_PK_COLUMN = "ID";

    public void setCause(String cause) {
        writeProperty("cause", cause);
    }
    public String getCause() {
        return (String)readProperty("cause");
    }
    
    
    public void setDate(java.util.Date date) {
        writeProperty("date", date);
    }
    public java.util.Date getDate() {
        return (java.util.Date)readProperty("date");
    }
    
    
    public void setStudentCode(String studentCode) {
        writeProperty("studentCode", studentCode);
    }
    public String getStudentCode() {
        return (String)readProperty("studentCode");
    }
    
    
    public void setProblem(cayenne.DBobjects.Problem problem) {
        setToOneTarget("problem", problem, true);
    }

    public cayenne.DBobjects.Problem getProblem() {
        return (cayenne.DBobjects.Problem)readProperty("problem");
    } 
    
    
    public void setStudent(cayenne.DBobjects.Student student) {
        setToOneTarget("student", student, true);
    }

    public cayenne.DBobjects.Student getStudent() {
        return (cayenne.DBobjects.Student)readProperty("student");
    } 
    
    
}
