package cayenne.DBobjects.auto;

import java.util.List;

/** Class _Category was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Category extends org.apache.cayenne.CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String PROBLEMS_PROPERTY = "problems";

    public static final String ID_PK_COLUMN = "ID";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void addToProblems(cayenne.DBobjects.Problem obj) {
        addToManyTarget("problems", obj, true);
    }
    public void removeFromProblems(cayenne.DBobjects.Problem obj) {
        removeToManyTarget("problems", obj, true);
    }
    public List getProblems() {
        return (List)readProperty("problems");
    }
    
    
}
