package cayenne.DBobjects.auto;

import java.util.List;

/** Class _Class was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Class extends org.apache.cayenne.CayenneDataObject {

    public static final String SEMESTER_PROPERTY = "semester";
    public static final String TITLE_PROPERTY = "title";
    public static final String YEAR_TAUGHT_PROPERTY = "yearTaught";
    public static final String PROBLEMS_PROPERTY = "problems";
    public static final String PROFESSOR_PROPERTY = "professor";
    public static final String STUDENTS_PROPERTY = "students";

    public static final String ID_PK_COLUMN = "ID";

    public void setSemester(String semester) {
        writeProperty("semester", semester);
    }
    public String getSemester() {
        return (String)readProperty("semester");
    }
    
    
    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }
    
    
    public void setYearTaught(Integer yearTaught) {
        writeProperty("yearTaught", yearTaught);
    }
    public Integer getYearTaught() {
        return (Integer)readProperty("yearTaught");
    }
    
    
    public void addToProblems(cayenne.DBobjects.Problem obj) {
        addToManyTarget("problems", obj, true);
    }
    public void removeFromProblems(cayenne.DBobjects.Problem obj) {
        removeToManyTarget("problems", obj, true);
    }
    public List getProblems() {
        return (List)readProperty("problems");
    }
    
    
    public void setProfessor(cayenne.DBobjects.Professor professor) {
        setToOneTarget("professor", professor, true);
    }

    public cayenne.DBobjects.Professor getProfessor() {
        return (cayenne.DBobjects.Professor)readProperty("professor");
    } 
    
    
    public void addToStudents(cayenne.DBobjects.Student obj) {
        addToManyTarget("students", obj, true);
    }
    public void removeFromStudents(cayenne.DBobjects.Student obj) {
        removeToManyTarget("students", obj, true);
    }
    public List getStudents() {
        return (List)readProperty("students");
    }
    
    
}
