package cayenne.DBobjects.auto;

import java.util.List;

/** Class _Problem was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Problem extends org.apache.cayenne.CayenneDataObject {

    public static final String CODE_PROPERTY = "code";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String INPUT_DATA_PROPERTY = "inputData";
    public static final String NAME_PROPERTY = "name";
    public static final String OUTPUT_DATA_PROPERTY = "outputData";
    public static final String ATTEMPT_PROPERTY = "attempt";
    public static final String AUTHOR_PROPERTY = "author";
    public static final String CATEGORY_PROPERTY = "category";
    public static final String CLASSES_PROPERTY = "classes";

    public static final String ID_PK_COLUMN = "ID";

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setInputData(String inputData) {
        writeProperty("inputData", inputData);
    }
    public String getInputData() {
        return (String)readProperty("inputData");
    }
    
    
    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }
    
    
    public void setOutputData(String outputData) {
        writeProperty("outputData", outputData);
    }
    public String getOutputData() {
        return (String)readProperty("outputData");
    }
    
    
    public void addToAttempt(cayenne.DBobjects.Attempt obj) {
        addToManyTarget("attempt", obj, true);
    }
    public void removeFromAttempt(cayenne.DBobjects.Attempt obj) {
        removeToManyTarget("attempt", obj, true);
    }
    public List getAttempt() {
        return (List)readProperty("attempt");
    }
    
    
    public void setAuthor(cayenne.DBobjects.Professor author) {
        setToOneTarget("author", author, true);
    }

    public cayenne.DBobjects.Professor getAuthor() {
        return (cayenne.DBobjects.Professor)readProperty("author");
    } 
    
    
    public void setCategory(cayenne.DBobjects.Category category) {
        setToOneTarget("category", category, true);
    }

    public cayenne.DBobjects.Category getCategory() {
        return (cayenne.DBobjects.Category)readProperty("category");
    } 
    
    
    public void addToClasses(cayenne.DBobjects.Class obj) {
        addToManyTarget("classes", obj, true);
    }
    public void removeFromClasses(cayenne.DBobjects.Class obj) {
        removeToManyTarget("classes", obj, true);
    }
    public List getClasses() {
        return (List)readProperty("classes");
    }
    
    
}
